# Cloudflare Tunnel Configuration
tunnel: f7e3682a-86c5-46a2-857a-8ee2c2d78e49
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # SSH access
  - hostname: rpi.mlovera.dev
    service: ssh://host.docker.internal:22
  
  # Wildcard for all other services handled by the proxy
  - hostname: "*.mlovera.dev"
    service: http://lab-proxy:80

  # Default rule
  - service: http_status:404
