version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: lab-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - /home/mlovera/lab/external/ollama/.env
    volumes:
      - /home/mlovera/lab/core/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/mlovera/lab/core/proxy/templates:/etc/nginx/templates:ro
      - /home/mlovera/lab/core/proxy/html:/usr/share/nginx/html:ro
    networks:
      - lab-network

networks:
  lab-network:
    external: true
