name: mongo-express

services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - lab-network

networks:
  lab-network:
    external: true
