name: n8n

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_local
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_BLOCK_PYTHON_SCRIPT_EXECUTION=false
      - N8N_RUNNERS_MODE=external
      - N8N_EXTERNAL_PYTHON_RUNNER_URL=http://python-runner:5000
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
    volumes:
      - ./data:/home/node/.n8n
      - ../../shared:/home/node/shared:ro
    networks:
      - lab-network
    deploy:
      resources:
        limits:
          memory: 2G

  python-runner:
    image: n8nio/runners:latest
    container_name: n8n_python_runner
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - lab-network

networks:
  lab-network:
    external: true